[package]
name = "espn-ffl"
version = "0.1.0"
edition = "2024"

[dependencies]
structopt = "0.3"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
once_cell = "1"
