[package]
name = "espn-ffl"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
thiserror = "1.0"
anyhow = "1.0"
