[test_config]
# Keep this minimal since CI workflow sets most options via command line

# Timeout for each test in seconds
timeout = "120s"

# Don't follow child processes
follow-exec = false

# Count hits in tests
count = true

# Exclude integration/I/O code that can't be unit tested
exclude-files = [
    "src/main.rs",
    "**/tests.rs",
    "**/tests/**"
]
