[test_config]
# Timeout for each test in seconds
timeout = "120s"

# Don't follow child processes
follow-exec = false

# Count hits in tests
count = true

# Skip unstable features that can cause issues
skip-clean = false

# Exclude integration/I/O code that can't be unit tested
exclude-files = [
    "src/main.rs",
    "**/tests.rs",
    "**/tests/**"
]
