name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin \
            --verbose \
            --all-features \
            --workspace \
            --timeout 120 \
            --exclude-files src/main.rs \
            --out xml \
            --output-dir coverage

          # Extract coverage percentage from XML
          COVERAGE=$(grep -o 'line-rate="[^"]*"' coverage/cobertura.xml | head -1 | sed 's/line-rate="//' | sed 's/"//')
          COVERAGE_PERCENT=$(echo "scale=1; $COVERAGE * 100" | bc)
          echo "Coverage: $COVERAGE_PERCENT%"
          echo "COVERAGE_PERCENT=$COVERAGE_PERCENT" >> $GITHUB_ENV

      - name: Create coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          # Create a simple coverage badge using shields.io endpoint style
          COVERAGE_INT=${COVERAGE_PERCENT%.*}
          if [ "$COVERAGE_INT" -ge 80 ]; then
            COLOR="brightgreen"
          elif [ "$COVERAGE_INT" -ge 60 ]; then
            COLOR="yellow"
          else
            COLOR="red"
          fi

          # Create badge JSON for shields.io endpoint
          mkdir -p badges
          cat > badges/coverage.json << EOF
          {
            "schemaVersion": 1,
            "label": "coverage",
            "message": "${COVERAGE_PERCENT}%",
            "color": "$COLOR"
          }
          EOF

      - name: Deploy badge to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: badges
          destination_dir: badges
          keep_files: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/cobertura.xml